In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.ticker as ticker
from matplotlib.axis import Axis
import datetime as dt

In [2]:
def get_data(filename):    
    data = pd.read_csv(filename)
    #data['time'] = pd.to_datetime(data['time'])  #.dt.tz_convert(None)
    #data.info()
    #print(data.tail(5))
    return data

In [3]:
data_file = "table-indicateurs-open-data-france-2023-06-30-17h59.csv"
# read data with pandas
data = get_data(data_file)
data.info()

In [7]:
data.set_index('date',inplace=True)
data

,tx_pos,tx_incid,TO,R,rea,hosp,rad,dchosp,incid_rea,incid_hosp,incid_rad,incid_dchosp,conf,conf_j1,pos,esms_dc,dc_tot,pos_7j,cv_dose1,esms_cas
date,,,,,,,,,,,,,,,,,,,,
2020-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-26,8.39,11.85,0.100040,NaN,506.0,8856.0,887379.0,137940.0,14.0,83.0,118.0,13.0,NaN,213.0,1741.0,29692.0,167632.0,8044.0,80.6,483245.0
2023-06-27,8.19,11.15,0.099644,NaN,504.0,8807.0,887496.0,137950.0,9.0,80.0,115.0,10.0,NaN,1680.0,1167.0,29692.0,167642.0,7570.0,NaN,483247.0
2023-06-28,NaN,NaN,0.098656,NaN,499.0,8721.0,887622.0,137954.0,2.0,63.0,141.0,4.0,NaN,1148.0,NaN,29692.0,167646.0,NaN,NaN,483249.0
2023-06-29,NaN,NaN,0.096876,NaN,490.0,8625.0,887766.0,137962.0,4.0,57.0,144.0,8.0,NaN,1106.0,NaN,29692.0,167654.0,NaN,NaN,483259.0
2023-06-30,NaN,NaN,0.094701,NaN,479.0,8540.0,887911.0,137972.0,3.0,65.0,143.0,10.0,NaN,985.0,NaN,29692.0,167664.0,NaN,NaN,483261.0

In [8]:
data_file = "table-indicateurs-open-data-dep-2023-06-30-17h59.csv"
# read data with pandas
data = get_data(data_file)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121200 entries, 0 to 121199
Data columns (total 22 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   dep            121200 non-null  object
 1   date           121200 non-null  object
 2   reg            121200 non-null  int64
 3   lib_dep        121200 non-null  object
 4   lib_reg        121200 non-null  object
 5   tx_pos         115241 non-null  float64
 6   tx_incid       115241 non-null  float64
 7   TO             121200 non-null  float64
 8   R              18050 non-null   float64
 9   hosp           121200 non-null  int64
 10  rea            121200 non-null  int64
 11  rad            121200 non-null  int64
 12  dchosp         121200 non-null  int64
 13  reg_rea        121200 non-null  int64
 14  incid_hosp     121099 non-null  float64
 15  incid_rea      121099 non-null  float64
 16  incid_rad      121099 non-null  float64
 17  incid_dchosp   121099 non-null  float64
 18  reg_incid_rea  121099 non-null  float64
 19  pos            115241 non-null  float64
 20  pos_7j         115241 non-null  float64
 21  cv_dose1       101 non-null     float64
dtypes: float64(12), int64(6), object(4)
memory usage: 20.3+ MB

C:\Users\jean\AppData\Local\Temp\ipykernel_17212\3765647283.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(filename)

In [9]:
data

,dep,date,reg,lib_dep,lib_reg,tx_pos,tx_incid,TO,R,hosp,...,dchosp,reg_rea,incid_hosp,incid_rea,incid_rad,incid_dchosp,reg_incid_rea,pos,pos_7j,cv_dose1
0,1,2020-03-18,84,Ain,Auvergne et Rhône-Alpes,NaN,NaN,0.062612,NaN,2,...,0,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2020-03-19,84,Ain,Auvergne et Rhône-Alpes,NaN,NaN,0.132379,NaN,2,...,0,79,1.0,0.0,0.0,0.0,44.0,NaN,NaN,NaN
2,1,2020-03-20,84,Ain,Auvergne et Rhône-Alpes,NaN,NaN,0.155635,NaN,2,...,0,87,0.0,0.0,1.0,0.0,16.0,NaN,NaN,NaN
3,1,2020-03-21,84,Ain,Auvergne et Rhône-Alpes,NaN,NaN,0.173524,NaN,4,...,0,88,3.0,0.0,0.0,0.0,15.0,NaN,NaN,NaN
4,1,2020-03-22,84,Ain,Auvergne et Rhône-Alpes,NaN,NaN,0.212880,NaN,8,...,0,106,3.0,1.0,1.0,0.0,25.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121195,976,2023-06-26,6,Mayotte,Mayotte,0.41,0.33,0.000000,NaN,1,...,163,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,54.2
121196,976,2023-06-27,6,Mayotte,Mayotte,0.43,0.33,0.000000,NaN,1,...,163,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN
121197,976,2023-06-28,6,Mayotte,Mayotte,NaN,NaN,0.000000,NaN,1,...,163,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
121198,976,2023-06-29,6,Mayotte,Mayotte,NaN,NaN,0.000000,NaN,1,...,163,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
121199,976,2023-06-30,6,Mayotte,Mayotte,NaN,NaN,0.000000,NaN,1,...,163,0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN